config/routes.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

Rails.application.routes.draw do
  resources :books
  resources :records
end

app/models/application_record.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class Book < ApplicationRecord
  has_ancestry
  has_many :entries

  validates_presence_of :name

  def balance
    entries.sum(:amount_subunits).to_money.format
  end

  def name_for_select
    "#{'−' * depth} #{name}"
  end

  def path_name
    path.pluck(:name).join('/')
  end

  def self.arrange_as_array(options={}, hash=nil)
    hash ||= arrange(options)

    arr = []
    hash.each do |node, children|
      arr << node
      arr += arrange_as_array(options, children) unless children.empty?
    end
    arr
  end
end

app/models/entry.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class Entry < ApplicationRecord
  belongs_to :book
  belongs_to :record

  def self.ordered(order)
    order = :desc if order.blank?
    joins(:record).
      order("records.date": order)
  end

  monetize :amount_subunits
end

app/models/record.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class Record < ApplicationRecord
  has_many :entries, dependent: :destroy
  accepts_nested_attributes_for :entries

  validates_presence_of :date
  validates_presence_of :description
end

app/controllers/application_controller.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  def index
    @books = Book.all
  end

  # GET /books/1
  def show
    @order = (params[:order] || 'desc').delete_prefix('date-').to_sym
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def book_params
      params[:book][:name].strip!
      params.require(:book).permit(:parent_id, :name, :notes).
        reject! { |k,v| k == 'parent_id' && v.blank? }
    end
end

app/controllers/records_controller.rb
# Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  def index
    @order = (params[:order] || 'desc').delete_prefix('date-').to_sym
    @records = Record.all.order date: @order
    @order = (@order == :desc ? :asc : :desc)
  end

  # GET /records/1
  def show
  end

  # GET /records/new
  def new
    @record = Record.new(entries: [ Entry.new, Entry.new])
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to @record, notice: 'Record was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /records/1
  def update
    if @record.update(record_params)
      redirect_to @record, notice: 'Record was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /records/1
  def destroy
    @record.destroy
    redirect_to records_url, notice: 'Record was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def record_params
      params.require(:record)
        .permit(:date, :description,
                entries_attributes: [ :id, :book_id, :amount, :note ])
    end
end

app/views/books/_form.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      h2 = "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      ul
        - @book.errors.full_messages.each do |message|
          li = message

  - if Book.any?
    .field
      = f.label :parent
      = f.collection_select :parent_id, Book.arrange_as_array,
        :id, :name_for_select, include_blank: true
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :notes
    = f.text_area :notes
  .actions = f.submit

app/views/books/edit.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

h1 Editing book

== render 'form'

=> link_to 'Show', @book
'|
=< link_to 'Back', books_path

app/views/books/index.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

h1 Listing books

table
  thead
    tr
      th Name
      th Balance
      th
      th
      th

  tbody
    - Book.arrange_as_array.each do |book|
      tr
        td = book.name_for_select
        td = book.balance
        td = link_to 'Show', book
        td = link_to 'Edit', edit_book_path(book)
        td = link_to 'Destroy', book, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Book', new_book_path

app/views/books/new.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

h1 New book

== render 'form'

= link_to 'Back', books_path

app/views/books/show.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

p#notice = notice

p
  strong Name:
  = @book.path_name

table
  thead
    tr
      th
        ' Date
        = link_to "#{@order == :desc ? '↓' : '↑'}",
          book_path(@book, order: "date-#{@order == :desc ? :asc : :desc}")
      th Description
      th Amount
      th Note

  tbody
    - @book.entries.ordered(@order).each do |entry|
      tr
        td = entry.record.date
        td = link_to entry.record.description, entry.record
        td = entry.amount.format
        td = entry.note

p
  strong Notes:
  = @book.notes

=> link_to 'Edit', edit_book_path(@book)
'|
=< link_to 'Back', books_path

app/views/layouts/application.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

doctype html
html
  head
    title = Rails.application.class.module_parent_name
    = csrf_meta_tags

    = javascript_include_tag 'application'

  body
    == yield

app/views/records/_form.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

= form_for @record do |f|
  - if @record.errors.any?
    #error_explanation
      h2 = "#{pluralize(@record.errors.count, "error")} prohibited this record from being saved:"
      ul
        - @record.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :date
    = f.text_field :date, type: :date
  .field
    = f.label :description
    = f.text_field :description

  = f.fields_for :entries do |attr|
    .entry
      = attr.label :book
      = attr.collection_select :book_id, Book.arrange_as_array,
        :id, :name_for_select
    .entry
      = attr.label :amount
      = attr.number_field :amount
    .entry
      = attr.label :note
      = attr.text_field :note

  .actions = f.submit

app/views/records/edit.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

h1 Editing record

== render 'form'

=> link_to 'Show', @record
'|
=< link_to 'Back', records_path

app/views/records/index.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

h1 Listing records

table
  thead
    tr
      th
        ' Date
        = link_to "#{@order == :desc ? '↑' : '↓'}", order: "date-#{@order}"
      th Description
      th
      th
      th

  tbody
    - @records.each do |record|
      tr
        td = record.date
        td = record.description
        td = link_to 'Show', record
        td = link_to 'Edit', edit_record_path(record)
        td = link_to 'Destroy', record, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Record', new_record_path

app/views/records/new.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

h1 New record

== render 'form'

= link_to 'Back', records_path

app/views/records/show.html.slim
/ Copyright © 2020 Olaf Meeuwissen <paddy-hack@member.fsf.org>
/
/ SPDX-License-Identifier: AGPL-3.0-or-later

p#notice = notice

p
  strong Date:
  = @record.date
p
  strong Description:
  = @record.description

table
  thead
    tr
      th Book
      th Amount
      th Note

  tbody
    - @record.entries.each do |entry|
      tr
        td = link_to entry.book.path_name, entry.book
        td = entry.amount.format
        td = entry.note

=> link_to 'Edit', edit_record_path(@record)
'|
=< link_to 'Back', records_path